# Generated by Django 5.1.7 on 2025-08-19 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroLotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('resumo', models.TextField()),
                ('introducao', models.TextField()),
                ('objetivos', models.TextField()),
                ('metodologia', models.TextField()),
                ('resultados', models.TextField(blank=True, null=True)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('status', models.CharField(choices=[('aguardando_conselho', 'Aguardando aprovação do conselho'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_andamento', 'Em andamento'), ('encerrado', 'Encerrado')], default='aguardando_conselho', max_length=30)),
                ('valor_fomento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='projetos_participantes', to=settings.AUTH_USER_MODEL)),
                ('centro_lotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos_institucionais.centrolotacao')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_coordenados', to=settings.AUTH_USER_MODEL)),
                ('grupos_pesquisa', models.ManyToManyField(blank=True, to='projetos_institucionais.grupopesquisa')),
                ('ods', models.ManyToManyField(blank=True, to='projetos_institucionais.ods')),
            ],
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('parcial', 'Parcial'), ('final', 'Final')], max_length=10)),
                ('anexo_pdf', models.FileField(upload_to='relatorios/')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='projetos_institucionais.projeto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('perfil', models.CharField(choices=[('professor', 'Professor'), ('aluno', 'Aluno'), ('gestor', 'Gestor')], max_length=20)),
                ('regime_trabalho', models.CharField(blank=True, max_length=50, null=True)),
                ('centro_lotacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.centrolotacao')),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.endereco')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
