# Generated by Django 5.1.7 on 2025-09-04 22:09

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import projetos_institucionais.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenciaFinanciadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Agência Financiadora',
                'verbose_name_plural': 'Agências Financiadoras',
            },
        ),
        migrations.CreateModel(
            name='CentroLotacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name': 'Centro de Lotação',
                'verbose_name_plural': 'Centros de Lotação',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2, verbose_name='UF')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='GrupoPesquisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Grupo de Pesquisa',
                'verbose_name_plural': 'Grupos de Pesquisa',
            },
        ),
        migrations.CreateModel(
            name='ODS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título')),
            ],
            options={
                'verbose_name': 'ODS',
                'verbose_name_plural': 'ODS',
            },
        ),
        migrations.CreateModel(
            name='TipoEtico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Tipo Ético',
                'verbose_name_plural': 'Tipos Éticos',
            },
        ),
        migrations.CreateModel(
            name='Titulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Titulação',
                'verbose_name_plural': 'Titulações',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('perfil', models.CharField(choices=[('coordenador', 'Coordenador'), ('aluno', 'Aluno'), ('gestor', 'Gestor')], max_length=20)),
                ('regime_trabalho', models.CharField(blank=True, max_length=3, null=True, verbose_name='Regime de Trabalho')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('centro_lotacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.centrolotacao', verbose_name='Centro de Lotação')),
                ('endereco', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.endereco')),
                ('titulacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.titulacao', verbose_name='Titulação')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CursoGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('centro_lotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos_institucionais.centrolotacao', verbose_name='Centro de Lotação')),
            ],
            options={
                'verbose_name': 'Curso de Graduação',
                'verbose_name_plural': 'Cursos de Graduação',
            },
        ),
        migrations.CreateModel(
            name='ProgramaPos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('centro_lotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos_institucionais.centrolotacao', verbose_name='Centro de Lotação')),
            ],
            options={
                'verbose_name': 'Programa de Pós-Graduação',
                'verbose_name_plural': 'Programas de Pós-Graduação',
            },
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('resumo', models.TextField()),
                ('introducao', models.TextField(verbose_name='Introdução')),
                ('objetivos', models.TextField()),
                ('metodologia', models.TextField()),
                ('resultados', models.TextField(blank=True, null=True)),
                ('referencias', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('status', models.CharField(choices=[('submetido', 'Submetido'), ('aguardando_conselho', 'Aguardando aprovação do conselho'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_andamento', 'Em andamento'), ('encerrado', 'Encerrado')], default='submetido', max_length=30)),
                ('valor_fomento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('AgenciaFinanciadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.agenciafinanciadora', verbose_name='Agência Financiadora')),
                ('alunos', models.ManyToManyField(blank=True, limit_choices_to={'perfil': 'aluno'}, related_name='projetos_participados', to=settings.AUTH_USER_MODEL)),
                ('centro_lotacao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projetos_institucionais.centrolotacao', verbose_name='Centro de Lotação')),
                ('coordenador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projetos_coordenados', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.cursograduacao', verbose_name='Curso de Graduação')),
                ('grupos_pesquisa', models.ManyToManyField(blank=True, to='projetos_institucionais.grupopesquisa', verbose_name='Grupos de Pesquisa')),
                ('ods', models.ManyToManyField(blank=True, to='projetos_institucionais.ods')),
                ('tipo_etica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.tipoetico', verbose_name='Tipo Ético')),
            ],
            options={
                'verbose_name': 'Projeto',
                'verbose_name_plural': 'Projetos',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('caminho_arquivo', models.FileField(upload_to=projetos_institucionais.models.caminho_upload_arquivo, verbose_name='Arquivo')),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='projetos_institucionais.projeto')),
            ],
        ),
        migrations.CreateModel(
            name='Ata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('data_reuniao', models.DateField(verbose_name='Data da Reunião')),
                ('arquivo_pdf', models.FileField(upload_to=projetos_institucionais.models.caminho_upload_arquivo)),
                ('enviado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atas', to='projetos_institucionais.projeto')),
            ],
            options={
                'verbose_name_plural': 'Atas',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('parcial', 'Parcial'), ('final', 'Final')], max_length=10)),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('anexo_pdf', models.FileField(upload_to=projetos_institucionais.models.caminho_upload_arquivo)),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='projetos_institucionais.projeto')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
    ]
