# Generated by Django 5.1.7 on 2025-09-22 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='eh_docente',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É docente?'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='eh_pesquisador',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É pesquisador?'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='eh_pesquisador_visitante',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='É pesquisador visitante?'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='etica_obrigatoria',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Envolve Aspectos Éticos?'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='introducao',
            field=models.TextField(blank=True, null=True, verbose_name='Introdução'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
