# Generated by Django 5.1.7 on 2025-09-22 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0002_alter_projeto_data_fim_alter_projeto_data_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='centro_lotacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='projetos_institucionais.centrolotacao', verbose_name='Centro de Lotação'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='participa_pos_graduacao',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Participa de Programa de Pós-Graduação?'),
        ),
    ]
