# Generated by Django 5.1.7 on 2025-09-24 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0003_alter_projeto_centro_lotacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
