# Generated by Django 5.1.7 on 2025-09-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0004_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Marque esta opção para ativar a conta do usuário.', verbose_name='Ativo'),
        ),
    ]
