# Generated by Django 5.1.7 on 2025-09-25 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0005_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='ods',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='ods_imagens/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetos_institucionais.cursograduacao', verbose_name='Curso de Graduação'),
        ),
    ]
