# Generated by Django 5.1.7 on 2025-09-25 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0006_ods_imagem_usuario_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='tipo_anexo',
            field=models.CharField(choices=[('comite_etica', 'Aprovação do Comitê de Ética'), ('cronograma', 'Cronograma'), ('imagens', 'Figuras, Imagens, etc.'), ('projeto_completo', 'Projeto Completo'), ('comprovante_aprovacao', 'Comprovante de Aprovação (Gestor)'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Anexo'),
        ),
    ]
