# Generated by Django 5.1.7 on 2025-09-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0007_alter_anexo_tipo_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ativo', 'Ativo'), ('inativo', 'Inativo')], default='pendente', max_length=20, verbose_name='Status'),
        ),
    ]
