# Generated by Django 5.1.7 on 2025-09-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0009_alter_anexo_tipo_anexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='projetos_capas/', verbose_name='Imagem de Capa'),
        ),
    ]
