# Generated by Django 5.1.7 on 2025-10-01 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0011_notificacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='centro_lotacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projetos_institucionais.centrolotacao', verbose_name='Centro de Lotação'),
        ),
    ]
