# Generated by Django 5.1.7 on 2025-10-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0012_alter_projeto_centro_lotacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data_envio',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
