# Generated by Django 5.1.7 on 2025-10-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0013_alter_relatorio_data_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido'), ('aguardando_conselho', 'Aguardando aprovação do conselho'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_andamento', 'Em andamento'), ('aguardando_encerramento', 'Aguardando Encerramento'), ('encerrado', 'Encerrado')], default='rascunho', max_length=30),
        ),
    ]
