# Generated by Django 5.1.7 on 2025-10-02 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0014_alter_projeto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Edital')),
                ('descricao', models.TextField(verbose_name='Descrição Resumida')),
                ('data_inicio_submissoes', models.DateField(verbose_name='Início das Submissões')),
                ('data_fim_submissoes', models.DateField(verbose_name='Fim das Submissões')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberto', 'Aberto'), ('fechado', 'Fechado')], default='rascunho', max_length=10)),
                ('documento_principal', models.FileField(upload_to='editais/documentos/', verbose_name='Documento Principal do Edital (PDF)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
                'ordering': ['-data_inicio_submissoes'],
            },
        ),
        migrations.CreateModel(
            name='AnexoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Anexo')),
                ('arquivo', models.FileField(upload_to='editais/anexos/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='projetos_institucionais.edital')),
            ],
            options={
                'verbose_name': 'Anexo do Edital',
                'verbose_name_plural': 'Anexos do Edital',
            },
        ),
        migrations.AddField(
            model_name='projeto',
            name='edital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projetos', to='projetos_institucionais.edital', verbose_name='Edital Vinculado'),
        ),
    ]
