# Generated by Django 5.1.7 on 2025-10-02 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0015_edital_anexoedital_projeto_edital'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edital',
            options={'ordering': ['-ano', '-numero'], 'verbose_name': 'Edital', 'verbose_name_plural': 'Editais'},
        ),
        migrations.AddField(
            model_name='edital',
            name='ano',
            field=models.PositiveIntegerField(default=2025, verbose_name='Ano do Edital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='numero',
            field=models.PositiveIntegerField(default=2025, verbose_name='Número do Edital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edital',
            name='tipo',
            field=models.CharField(default='PROPEG', help_text='Ex: PROPEG, PROEX, etc.', max_length=50, verbose_name='Tipo/Origem'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título Descritivo do Edital'),
        ),
        migrations.AlterUniqueTogether(
            name='edital',
            unique_together={('numero', 'ano', 'tipo')},
        ),
    ]
