# Generated by Django 5.1.7 on 2026-03-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0016_alter_edital_options_edital_ano_edital_numero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipeprojeto',
            name='funcao',
            field=models.CharField(choices=[('coordenador_auxiliar', 'Coordenador Auxiliar'), ('pesquisador', 'Pesquisador'), ('aluno_bolsista', 'Aluno Bolsista'), ('aluno_voluntario', 'Aluno Voluntário'), ('aluno_pesquisador', 'Aluno Pesquisador'), ('tecnico', 'Técnico'), ('colaborador', 'Colaborador'), ('outro', 'Outro')], default='colaborador', max_length=50, verbose_name='Função na Equipe'),
        ),
    ]
