# Generated by Django 5.1.7 on 2026-03-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0017_equipeprojeto_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cnpq',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº Currículo Lattes/CNPq'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='siape',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SIAPE'),
        ),
    ]
