# Generated by Django 5.1.7 on 2026-03-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0018_usuario_cnpq_usuario_data_nascimento_usuario_rg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cnpq_area',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grande Área CNPq'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lattes',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nº Currículo Lattes'),
        ),
    ]
