# Generated by Django 5.1.7 on 2026-03-17 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0019_usuario_cnpq_area_usuario_lattes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cnpq_area',
            field=models.CharField(blank=True, choices=[('', 'Selecione uma área'), ('Ciências Exatas e da Terra', [('exatas_matematica', 'Matemática'), ('exatas_computacao', 'Computação'), ('exatas_fisica', 'Física'), ('exatas_quimica', 'Química'), ('exatas_geociencias', 'Geociências')]), ('Ciências Biológicas', [('bio_geral', 'Biologia Geral'), ('bio_biofisica', 'Biofísica'), ('bio_botanica', 'Botânica'), ('bio_ecologia', 'Ecologia'), ('bio_genetica', 'Genética')]), ('Engenharias', [('eng_civil', 'Engenharia Civil'), ('eng_eletrica', 'Engenharia Elétrica'), ('eng_mecanica', 'Engenharia Mecânica'), ('eng_producao', 'Engenharia de Produção')]), ('Ciências da Saúde', [('saude_medicina', 'Medicina'), ('saude_nutricao', 'Nutrição'), ('saude_coletiva', 'Saúde Coletiva')]), ('Ciências Agrárias', [('agrar_agronomia', 'Agronomia'), ('agrar_florestal', 'Recursos Florestais'), ('agrar_zootecnia', 'Zootecnia')]), ('Ciências Sociais Aplicadas', [('sociais_direito', 'Direito'), ('sociais_admin', 'Administração'), ('sociais_economia', 'Economia'), ('sociais_info', 'Ciência da Informação')]), ('Ciências Humanas', [('humanas_filosofia', 'Filosofia'), ('humanas_sociologia', 'Sociologia'), ('humanas_historia', 'História'), ('humanas_psicologia', 'Psicologia'), ('humanas_educacao', 'Educação')]), ('Linguística, Letras e Artes', [('lla_linguistica', 'Linguística'), ('lla_letras', 'Letras'), ('lla_artes', 'Artes')])], max_length=100, null=True, verbose_name='Grande Área CNPq'),
        ),
    ]
