# Generated by Django 5.1.7 on 2026-03-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0020_alter_usuario_cnpq_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='objetivo_geral',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivo Geral'),
        ),
        migrations.AddField(
            model_name='projeto',
            name='objetivos_especificos',
            field=models.TextField(blank=True, null=True, verbose_name='Objetivos Específicos'),
        ),
    ]
