# Generated by Django 5.1.7 on 2026-03-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0021_projeto_objetivo_geral_projeto_objetivos_especificos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='matricula',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº de Matrícula'),
        ),
    ]
