# Generated by Django 5.1.7 on 2026-03-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0022_usuario_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='tipo_anexo',
            field=models.CharField(choices=[('comite_etica', 'Aprovação do Comitê de Ética'), ('cronograma', 'Cronograma'), ('imagens', 'Figuras, Imagens, etc.'), ('projeto_completo', 'Projeto Completo'), ('comprovante_aprovacao', 'Comprovante de Aprovação (Gestor)'), ('ata_conselho', 'Ata de Aprovação do Conselho'), ('relatorio_submissao', 'Relatório de Submissão (Automático)'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Anexo'),
        ),
    ]
