# Generated by Django 5.1.7 on 2026-03-18 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0023_alter_anexo_tipo_anexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdendoEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título do Adendo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='editais/adendos/', verbose_name='Arquivo do Adendo (PDF, opcional)')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adendos', to='projetos_institucionais.edital')),
            ],
            options={
                'verbose_name': 'Adendo do Edital',
                'verbose_name_plural': 'Adendos do Edital',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
