# Generated by Django 5.1.7 on 2026-03-19 14:34

import django.core.files.storage
import projetos_institucionais.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0024_adendoedital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adendoedital',
            name='arquivo',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='editais/adendos/', verbose_name='Arquivo do Adendo (PDF, opcional)'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='anexos/%Y/%m/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='anexoedital',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='editais/anexos/'),
        ),
        migrations.AlterField(
            model_name='ata',
            name='arquivo_pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=projetos_institucionais.models.caminho_upload_arquivo),
        ),
        migrations.AlterField(
            model_name='documento',
            name='caminho_arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=projetos_institucionais.models.caminho_upload_arquivo, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='edital',
            name='documento_principal',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='editais/documentos/', verbose_name='Documento Principal do Edital (PDF)'),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='anexo_pdf',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to=projetos_institucionais.models.caminho_upload_arquivo),
        ),
    ]
