# Generated by Django 5.1.7 on 2026-03-19 15:32

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0025_alter_adendoedital_arquivo_alter_anexo_arquivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edital',
            name='documento_principal',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='editais/documentos/', verbose_name='Documento Principal do Edital (PDF)'),
        ),
    ]
