# Generated by Django 5.1.7 on 2026-03-19 17:50

import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0027_alter_adendoedital_arquivo_alter_anexo_arquivo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(max_length=500, storage=django.core.files.storage.FileSystemStorage(), upload_to='relatorios/evidencias/')),
                ('descricao', models.CharField(blank=True, default='', max_length=255)),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='projetos_institucionais.relatorio')),
            ],
            options={
                'verbose_name': 'Evidência de Relatório',
                'verbose_name_plural': 'Evidências de Relatório',
            },
        ),
    ]
