# Generated by Django 5.1.7 on 2026-03-20 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0028_evidenciarelatorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='participa_pos_graduacao',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Vinculado a Programa de Pós-Graduação?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='programa_pos_vinculo',
            field=models.CharField(blank=True, choices=[('', 'Selecione o programa'), ('PPGCA', 'Ciências Ambientais (PPGCA)'), ('PPGCC', 'Ciência da Computação (PPGCC)'), ('PPGCF', 'Ciência Florestal (PPGCF)'), ('PPGCSA', 'Ciência da Saúde na Amazônia Ocidental (PPGCSA)'), ('PPGCITA', 'Ciência, Inovação e Tecnologia para a Amazônia (PPGCITA)'), ('PPGDR', 'Desenvolvimento Regional (PPGDR)'), ('PPGECOL', 'Ecologia e Manejo de Recursos Naturais (PPGECOL)'), ('PPGEDU', 'Educação (PPGEDU)'), ('PPGEF', 'Ensino de Física — Mestrado Profissional (PPGEF)'), ('PPGECM', 'Ensino de Ciências e Matemática — Mestrado Profissional (PPGECM)'), ('PPEHL', 'Ensino de Humanidades e Linguagens (PPEHL)'), ('PPGGEO', 'Geografia (PPGGEO)'), ('PPGLL', 'Letras: Linguagem e Identidade (PPGLL)'), ('PROFMAT', 'Matemática em Rede Nacional — Mestrado Profissional (PROFMAT)'), ('PPGAPV', 'Agronomia: Produção Vegetal (PPGAPV)'), ('PPGAC', 'Artes Cênicas (PPGAC)'), ('PPGBIONORTE', 'Biodiversidade e Biotecnologia — Rede Bionorte (PPGBIONORTE)'), ('PPGSC', 'Saúde Coletiva (PPGSC)'), ('PPGSPA', 'Sanidade e Produção Animal (PPGSPA)')], max_length=20, null=True, verbose_name='Programa de Pós-Graduação'),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='tipo_anexo',
            field=models.CharField(choices=[('comite_etica', 'Aprovação do Comitê de Ética'), ('cronograma', 'Cronograma'), ('imagens', 'Figuras, Imagens, etc.'), ('projeto_completo', 'Projeto Completo'), ('comprovante_aprovacao', 'Comprovante de Aprovação (Gestor)'), ('ata_conselho', 'Ata de Aprovação do Centro'), ('relatorio_submissao', 'Relatório de Submissão (Automático)'), ('outro', 'Outro')], max_length=50, verbose_name='Tipo de Anexo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('submetido', 'Submetido'), ('aguardando_conselho', 'Aguardando aprovação do Centro'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado'), ('em_andamento', 'Em andamento'), ('aguardando_encerramento', 'Aguardando Encerramento'), ('encerrado', 'Encerrado')], default='rascunho', max_length=30),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='lattes',
            field=models.URLField(blank=True, null=True, verbose_name='Link Currículo Lattes'),
        ),
    ]
