# Generated by Django 5.1.7 on 2026-09-15

from django.db import migrations, models


def classificar_projetos_existentes(apps, schema_editor):
    Projeto = apps.get_model('projetos_institucionais', 'Projeto')
    Anexo = apps.get_model('projetos_institucionais', 'Anexo')

    Projeto.objects.filter(agencia_financiadora__isnull=False).update(
        tipo_projeto='agencia_fomento'
    )
    Projeto.objects.filter(
        agencia_financiadora__isnull=True,
        edital__isnull=False,
    ).update(tipo_projeto='ufac_com_financiamento')
    Projeto.objects.filter(
        agencia_financiadora__isnull=True,
        edital__isnull=True,
    ).update(tipo_projeto='ufac_sem_financiamento')

    Anexo.objects.filter(
        projeto__tipo_projeto='agencia_fomento',
        tipo_anexo='comprovante_aprovacao',
        descricao__icontains='agência financiadora',
    ).update(tipo_anexo='comprovante_fomento')
    Anexo.objects.filter(
        projeto__tipo_projeto='agencia_fomento',
        tipo_anexo='outro',
        descricao__icontains='Documento do projeto aprovado',
    ).update(tipo_anexo='projeto_completo')


def reverter_classificacao(apps, schema_editor):
    Projeto = apps.get_model('projetos_institucionais', 'Projeto')
    Anexo = apps.get_model('projetos_institucionais', 'Anexo')

    Anexo.objects.filter(tipo_anexo='comprovante_fomento').update(
        tipo_anexo='comprovante_aprovacao'
    )
    Projeto.objects.update(tipo_projeto='')


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0029_usuario_participa_pos_graduacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='tipo_projeto',
            field=models.CharField(
                blank=True,
                choices=[
                    ('agencia_fomento', '1 - Projeto Aprovado (Agência de Fomento)'),
                    ('ufac_sem_financiamento', '2 - UFAC (Sem Financiamento/Fluxo Contínuo)'),
                    ('ufac_com_financiamento', '3 - UFAC (Com Financiamento)'),
                ],
                default='',
                max_length=40,
                verbose_name='Tipo de Projeto',
            ),
        ),
        migrations.AlterField(
            model_name='anexo',
            name='tipo_anexo',
            field=models.CharField(
                choices=[
                    ('comite_etica', 'Aprovação do Comitê de Ética'),
                    ('cronograma', 'Cronograma'),
                    ('imagens', 'Figuras, Imagens, etc.'),
                    ('projeto_completo', 'Projeto Completo'),
                    ('comprovante_fomento', 'Comprovante de Aprovação da Agência de Fomento'),
                    ('comprovante_aprovacao', 'Comprovante de Aprovação (Gestor)'),
                    ('ata_conselho', 'Ata de Aprovação do Centro'),
                    ('relatorio_submissao', 'Relatório de Submissão (Automático)'),
                    ('outro', 'Outro'),
                ],
                max_length=50,
                verbose_name='Tipo de Anexo',
            ),
        ),
        migrations.RunPython(classificar_projetos_existentes, reverter_classificacao),
    ]
