# Generated by Django 5.1.7 on 2026-09-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetos_institucionais', '0037_classificar_comprovantes_eticos_existentes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='regime_trabalho',
            field=models.CharField(blank=True, choices=[('20h', '20h'), ('40h', '40h'), ('DE', 'DE (Dedicação Exclusiva)')], max_length=3, null=True, verbose_name='Regime de Trabalho'),
        ),
    ]
